In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame()

In [ ]:
df["ad"]=["Ali", "Sevda","Nicat","Vuqar","Senan"]
df["yash"]=[19,21,30,27,34]
df["bal"]=[75,96,83,71,66]

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df.head(3)

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83

In [ ]:
df.tail(3)

      ad  yash  bal
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df.sample(2)

      ad  yash  bal
4  Senan    34   66
0    Ali    19   75

In [ ]:
df.sample(frac=0.5)

      ad  yash  bal
3  Vuqar    27   71
1  Sevda    21   96

In [ ]:
df.shape

(5, 3)

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns

Index(['ad', 'yash', 'bal'], dtype='object')

In [ ]:
len(df)

5

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df[df.yash>25]

      ad  yash  bal
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df[df.ad.str.startswith("S")]

      ad  yash  bal
1  Sevda    21   96
4  Senan    34   66

In [ ]:
df.dtypes

ad      object
yash     int64
bal      int64
dtype: object

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df[(df.yash>20) & (df.yash<25) ]

      ad  yash  bal
1  Sevda    21   96

In [ ]:
df[(df.ad.str.startswith("S")) & (df.yash>25)]

      ad  yash  bal
4  Senan    34   66

In [ ]:
df[(df.ad.str.startswith("S")) | (df.yash>25)]

      ad  yash  bal
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df.iloc[:,[1,2]]

   yash  bal
0    19   75
1    21   96
2    30   83
3    27   71
4    34   66

In [ ]:
df.iloc[2:5,[1,2]]

   yash  bal
2    30   83
3    27   71
4    34   66

In [ ]:
df.iloc[2:5,1:3]

   yash  bal
2    30   83
3    27   71
4    34   66

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df.loc[:,["yash","bal"]]

   yash  bal
0    19   75
1    21   96
2    30   83
3    27   71
4    34   66

In [ ]:
df

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df["fenn"]=["ML","BigData","CV","Cloud","Python"]

In [ ]:
df

      ad  yash  bal     fenn
0    Ali    19   75       ML
1  Sevda    21   96  BigData
2  Nicat    30   83       CV
3  Vuqar    27   71    Cloud
4  Senan    34   66   Python

In [ ]:
df2=df.loc[:,"ad":"bal"]

In [ ]:
df2

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df2.to_excel("student_data.xlsx", index=False)

In [ ]:
df3 = pd.read_excel("student_data.xlsx")

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3.nlargest(3,"yash")

      ad  yash  bal
4  Senan    34   66
2  Nicat    30   83
5   Vafa    30   70

In [ ]:
df3.nsmallest(3,"bal")

      ad  yash  bal
4  Senan    34   66
5   Vafa    30   70
3  Vuqar    27   71

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3.drop_duplicates(subset="yash",keep="last", inplace=True)

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3.sort_values(by="yash", ascending=False)

      ad  yash  bal
4  Senan    34   66
5   Vafa    30   70
3  Vuqar    27   71
1  Sevda    21   96
0    Ali    19   75

In [ ]:
df3 = pd.read_excel("student_data.xlsx")

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3.sort_values(by=["yash","bal"], ascending=[False,True])

      ad  yash  bal
4  Senan    34   66
5   Vafa    30   70
2  Nicat    30   83
3  Vuqar    27   71
1  Sevda    21   96
0    Ali    19   75

In [ ]:
df3.sort_values(by=["ad","yash","bal"], ascending=[True,False,True])

      ad  yash  bal
0    Ali    19   75
2  Nicat    30   83
4  Senan    34   66
1  Sevda    21   96
5   Vafa    30   70
3  Vuqar    27   71

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3[df3.yash==30]

      ad  yash  bal
2  Nicat    30   83
5   Vafa    30   70

In [ ]:
df3[df3.yash!=30]

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
3  Vuqar    27   71
4  Senan    34   66

In [ ]:
df3

      ad  yash  bal
0    Ali    19   75
1  Sevda    21   96
2  Nicat    30   83
3  Vuqar    27   71
4  Senan    34   66
5   Vafa    30   70

In [ ]:
df3.rename(columns={"bal":"qiymet"}, inplace=True)

In [ ]:
df3

      ad  yash  qiymet
0    Ali    19      75
1  Sevda    21      96
2  Nicat    30      83
3  Vuqar    27      71
4  Senan    34      66
5   Vafa    30      70

In [ ]:
df3.iloc[1,2]=70

In [ ]:
df3

      ad  yash  qiymet
0    Ali    19      75
1  Sevda    21      70
2  Nicat    30      83
3  Vuqar    27      71
4  Senan    34      66
5   Vafa    30      70

In [ ]:
df3.yash.mean()

26.833333333333332

In [ ]:
df3.yash.std()

5.776388721914987

In [ ]:
df3.yash.sum()

161

In [ ]:
df3.describe()

            yash     qiymet
count   6.000000   6.000000
mean   26.833333  72.500000
std     5.776389   5.890671
min    19.000000  66.000000
25%    22.500000  70.000000
50%    28.500000  70.500000
75%    30.000000  74.000000
max    34.000000  83.000000

In [ ]:
df3.describe(include="object")

         ad
count     6
unique    6
top     Ali
freq      1

In [ ]:
df3

      ad  yash  qiymet
0    Ali    19      75
1  Sevda    21      70
2  Nicat    30      83
3  Vuqar    27      71
4  Senan    34      66
5   Vafa    30      70

In [ ]:
df3.iloc[0,0]="Nicat"

In [ ]:
df3

      ad  yash  qiymet
0  Nicat    19      75
1  Sevda    21      70
2  Nicat    30      83
3  Vuqar    27      71
4  Senan    34      66
5   Vafa    30      70

In [ ]:
df3.describe(include="object")

           ad
count       6
unique      5
top     Nicat
freq        2